### ISSUE TITLE
スペイン語リソースに日本語文字列が多数入っている

### ISSUE THREAD

**Issue by doraTeX** [sonoisa/OgreKit#8]
[スペイン語リソース](https://github.com/sonoisa/OgreKit/blob/master/FindPanel/Resources/Spanish.lproj/OgreAdvancedFindPanel.nib/designable.nib)の中に，Tool Tip 文字列として日本語の文字列が多数残っています。
他の言語リソースでは，ローカライズしきれない Tool Tip 文字列は，英語に合わせるまたは空にする扱いになっていますので，スペイン語リソースでもそれに準じるのがよいと思います。

**Comment by sonoisa** [comment]
ご指摘ありがとうございます。修正いたしました。
